### ISSUE TITLE
Some info is not correct 

### ISSUE THREAD

**Issue by pkagiantas** [Tjeerdie/SPECTRE#10]
Baro is working when set to pin Α13 on Tuner Studio not on A9 

JP15 ( Flex fuel or Boot0 ) does not existing in V5.2 

Halleffect or VR input VR1 default on V5.2 is on HALL not on VR 

on the Jumper section you have (  Ignition 6 or GND ) for the IGN7 

thats what i have found so far it might help someone 
your master is working fine on my engine ( kawasaki z1000 ) 
( cant get a good cam signal to run sequential but i think that is not related to the board )

the only thinks missing is the datalogging on the sd ( its a must for a bike if you want to road tune it ) 
quick shifter would be nice too but cant get it all :P 

also what is the latest board version 5.2 or 5.3 or 5.4 ?

**Comment by Tjeerdie** [comment]
Thanks! I checked all of them and changed most of them in the readme

Except the VR1 being default to VR, because that is actually the case. (I use the VR sensor and the jumper is in the default setting)
