### ISSUE TITLE
Most 'stable' version?

### ISSUE THREAD

**Issue by wilmardo** [Tjeerdie/SPECTRE#13]
Hi!

The README states:

> Latest version is 0.5.2

But in the repo `0.5.3` and `0.5.4` are present. Does higher equal better?

**Comment by Tjeerdie** [comment]
Hi

I see i made a mistake, The latest tested and build version by me is 0.5.3 The 0.5.4 is the same schematic but clean-up schematic and using resistor arrays rather than individual resistors by @VitorBoss. I never build one of those but as the schematic is the same it should still work.
