### ISSUE TITLE
Partly assembled PCB

### ISSUE THREAD

**Issue by anyoneeee** [Tjeerdie/SPECTRE#14]
Hi, I´m not really into electronics, but I gave it a try and ordered some PCB from PCBWay. They partly assembled the board. Now I see that all the mosfets weren´t in the BOM I found (it´s V0.5.3 btw). At Q10 is not very much space to D37. Do I need D37? What is D37? Where do I find a complete BOM? Do you have pictures of your board? I can´t find any pictures from people that have built the board. So many questions... 
![PXL_20240112_204237662](https://github.com/Tjeerdie/SPECTRE/assets/156471856/7c3e77d7-295d-4cfb-a080-b3e5ce62aefc)
![PXL_20240112_204217603](https://github.com/Tjeerdie/SPECTRE/assets/156471856/bce243b1-1bc7-46c0-bf3c-95d3cb7f5da8)

**Comment by Tjeerdie** [comment]
Hi anyoneeee

First of all i will add to the read-me that it might be a good idea to be familiar with electronics before building this board. It all works if build with according to the schematics. But you might need to fiddle a bit to get some things working for your specific application.  Also soldering parts yourself is required.

I will add to the read-me that the jlc-pcb bom list is not complete, mostly because they do not have all the parts in their inventory.  And also assembly on the bottom side is not supported by JLC pcb. And no thu-hole components are assembled by JLC. I am actually surprised the BOM list still worked! Because usually parts are added/removed from the inventory list on a regular basis. The full BOM list could easily be generated from Kicad using the schematic

The BSP78 I used is also hard to come by now days. So a IRFL024N is a non protected mosfet that i used as a alternative. But it has no protection so it is easier to blow one up when somethings are connected wrong. 

I will add some pictures of one of my boards assembled to the point that I could use it.

**Comment by anyoneeee** [comment]
Hi Tjeerdie, thank you for the quick answer. Knowing how to use KiCad a little bit helps too and reading the description also 😄 . I ordered the BSP78, very cool MOSFET. I didn´t know they could have a short circuit protection in that little thing. Pictures of your assembled boards would be very helpful for me. Did you already use the board on other engines than the 4 cylinder in the description? Thank you for your support.

From your description:
Zener diodes
If you build the board with the injector driver mosfets to be BSP78 [Q10,Q11,Q13,Q14,Q18,Q19,Q20,Q21] you can leave the bzx84C39 + 1N4148 out [33,D34,D35,D36,D37,D38,D39,D40,D41,D42,D43,D44,D45,D46,D47,D48]. These are used for clamping, but the BSP78 has internal clamping. You can use other mosfets with SOT223 footprint in place of the BSP78. If these are not clamped or reptetative avalanch rated use the clamping diodes to keep them in spec.



![image](https://github.com/Tjeerdie/SPECTRE/assets/156471856/f1ffec75-615d-49d4-bb99-ebf0b55def74)
![image](https://github.com/Tjeerdie/SPECTRE/assets/156471856/c31ba2df-32b6-4358-9e94-fda9a20962dd)

#,"Reference","Qty","Value","Footprint","DNP"
--
1,"A1","1","Pololu_Breakout_DRV8825","Module:Pololu_Breakout-16_15.2x20.3mm",""
2,"C1, C2, C9, C10, C13, C19, C21,   C22, C25, C26, C29, C30, C31,   C32","14","100nf","Speeduino_base:C0603",""
3,"C3, C4, C8, C11, C14, C16, C17,   C20, C23, C24, C27,   C28","12","220nf","Speeduino_base:C0603",""
4,"C5,   C7","2","1nf","Speeduino_base:C0603",""
5,"C6,   C15","2","10uf","Speeduino_base:C1206",""
6,"C12,   C18","2","470uF   6.3V","Capacitor_SMD:CP_Elec_6.3x7.7",""
7,"D1, D2, D3, D5, D7, D9, D10, D11,   D12, D15, D16, D17, D19, D21, D22,   D24","16","BAT54S","Speeduino_base:SOT23",""
8,"D4, D14, D20, D30, D31,   D32","6","1N4007","Diode_SMD:D_SMA",""
9,"D6","1","Zener   3.6V","Diode_SMD:D_MiniMELF_Handsoldering",""
10,"D8","1","Zener   5.1V","Diode_SMD:D_MiniMELF_Handsoldering",""
11,"D13, D18, D26, D27, D28,   D29","6","YEL","Speeduino_base:LED-0603",""
12,"D33, D35, D36, D39, D40, D43,   D44,   D45","8","1N4148WS","Diode_SMD:D_SOD-323",""
13,"D34, D37, D38, D41, D42, D46,   D47,   D48","8","BZX84C39","Diode_SMD:D_SOT-23_ANK",""
14,"F1,   F2","2","PPTC   16V2A","Resistor_SMD:R_1812_4532Metric_Pad1.30x3.40mm_HandSolder",""
15,"J1","1","Conn_01x06_Male","Connector_PinHeader_2.54mm:PinHeader_1x06_P2.54mm_Vertical",""
16,"J2","1","Conn_02x04_Odd_Even","Speeduino_base:PinHeader_2x04_P2.54mm_Vertical",""
17,"J3","1","ProtoArea","Speeduino_base:Proto_area",""
18,"JP1,   JP4","2","Jumper_NO_Small","Jumper:SolderJumper-2_P1.3mm_Open_Pad1.0x1.5mm",""
19,"JP2, JP3, JP5, JP6, JP7, JP8,   JP9, JP10, JP15, JP16,   JP18","11","SolderJumper_3_Bridged12","Jumper:SolderJumper-3_P1.3mm_Bridged12_Pad1.0x1.5mm",""
20,"JP11,   JP12","2","PINHD-2X24","Speeduino_base:2X24",""
21,"JP13","1","Jumper_NC_Small","Jumper:SolderJumper-2_P1.3mm_Bridged_Pad1.0x1.5mm",""
22,"JP14","1","Jumper_NO_Small","Connector_PinHeader_2.54mm:PinHeader_1x02_P2.54mm_Vertical",""
23,"Q1, Q6, Q7,   Q12","4","AO3400","Speeduino_base:SOT-23",""
24,"Q10, Q11, Q13, Q14, Q15, Q16,   Q17, Q18, Q19, Q20,   Q21","11","BSP78","Speeduino_base:SOT223",""
25,"R1, R22, R31, R42,   R57","5","2k49","Speeduino_base:R0603",""
26,"R2","1","VARISTOR-18V","Varistor:RV_Disc_D12mm_W3.9mm_P7.5mm",""
27,"R3, R12, R15, R21, R32, R35,   R65, R68,   R69","9","1k","Speeduino_base:R0603",""
28,"R4, R6, R8, R18, R23, R24, R27,   R33, R37, R41, R49, R50, R55, R60, R61, R64,   R77","17","470R","Speeduino_base:R0603",""
29,"R5, R11, R13, R14, R16, R19,   R36, R59, R66, R79, R80, R81, R82, R86, R87, R88, R89, R90, R91,   R92","20","10k","Speeduino_base:R0603",""
30,"R7, R17, R38, R58, R62, R63,   R70,   R71","8","10R","Resistor_SMD:R_0603_1608Metric_Pad1.05x0.95mm_HandSolder",""
31,"R9, R25, R28,   R46","4","4k7","Speeduino_base:R0603",""
32,"R10, R26, R29,   R47","4","9k1","Speeduino_base:R0603",""
33,"R20","1","0R0","Speeduino_base:R0603",""
34,"R30","1","1k8","Speeduino_base:R0603",""
35,"R34, R39, R40, R43, R48, R51,   R52, R53, R54, R56, R67, R76, R78, R83, R84,   R85","16","100R","Speeduino_base:R0603",""
36,"R44","1","33k","Speeduino_base:R0603",""
37,"R45","1","5k1","Speeduino_base:R0603",""
38,"R74","1","120R","Speeduino_base:R0603",""
39,"R75","1","220R","Speeduino_base:R0603",""
40,"U1","1","MAX9926UAEE+","Speeduino_base:21-0055H_16",""
41,"U2","1","LM78M05_TO220","Package_TO_SOT_THT:TO-220-3_Horizontal_TabUp",""
42,"U3","1","TL431DBZ","Package_TO_SOT_SMD:SOT-23",""
43,"U4","1","molex_48pin","Speeduino_base:Molex_48",""
44,"U5","1","TJA1050","Package_SO:SO-8_5.3x6.2mm_P1.27mm",""
45,"U6","1","MAX3232","Package_SO:SOIC-16_4.55x10.3mm_P1.27mm",""
46,"U7, U8, U9,   U10","4","MIC4427","Package_SO:SO-8_3.9x4.9mm_P1.27mm",""
47,"U$1","1","WIRELESS-BLUETOOTH-HC-05","Speeduino_base:WIRELESS-BLUETOOTH-HC-05",""

**Comment by anyoneeee** [comment]
Assembled most of the parts today. Only the HC-05 Bluetooth module and the MAX9926UAEE+ VR Sensor Interface are missing.

![PXL_20240119_184140208 PORTRAIT ORIGINAL](https://github.com/Tjeerdie/SPECTRE/assets/156471856/b9970a6b-b96d-4270-9f37-919d5208e9f4)
![PXL_20240119_184348754 PORTRAIT ORIGINAL](https://github.com/Tjeerdie/SPECTRE/assets/156471856/1f703ec4-5769-478c-890d-3ced827f1e34)
![PXL_20240119_184508631 PORTRAIT ORIGINAL](https://github.com/Tjeerdie/SPECTRE/assets/156471856/a160e0ef-8b3c-4cdc-8cf1-990177d8b52e)
![PXL_20240119_184615804 PORTRAIT ORIGINAL](https://github.com/Tjeerdie/SPECTRE/assets/156471856/63dffa05-cfbf-4540-8c4e-c1034b827bda)
