### ISSUE TITLE
BOM file is not complete 

### ISSUE THREAD

**Issue by pkagiantas** [Tjeerdie/SPECTRE#2]
some of the parts have no designation like like the 26 10K resistors etc

**Comment by Tjeerdie** [comment]
Ah thanks! fixed it. I used it myself to build the board en removed all numbers already placed on the board. Now i repopulated it again with the latest full BOM.

**Comment by pkagiantas** [comment]
cool i ended up finding everything from the eeschema some parts are wrong labeled from the v5.2 schematics

**Comment by Tjeerdie** [comment]
you can easily export the same style BOM from kicad. No need to find them by hand!

**Comment by pkagiantas** [comment]
thanks ill give it a go 

one more question i did got some v5 by mistake do those work ok should i make them or not bother with them ?

**Comment by Tjeerdie** [comment]
I have 3 V0.5.2 bare/unpopulated boards here still. I had my engine running on a V0.5.1 and there is another 6 cylinder engine out there that runs an adapted V0.5.1. But i would start with the V0.5.2 that one is the latest the other designs are just put online for reference.

**Comment by pkagiantas** [comment]
yeah i received them today 5 of the v5.2 and 5 of the v5 ( by mistake ) i started on V5.2 to test on a bike engine but i was asking if i should keep the v5 or throw them away

**Comment by Tjeerdie** [comment]
ah now i understand. The V0.5.0 should work i think... I see some resistor values need tweaking to the new value (like for crank and cam). But in general it could work. but no guarantee.

**Comment by pkagiantas** [comment]
cool no wories ! more project to fiddle with ;P
