### ISSUE TITLE
 Q12/Q6 Function ?

### ISSUE THREAD

**Issue by pkagiantas** [Tjeerdie/SPECTRE#5]
hey hi im making my second one 5.2 ! 

what are the Q12 and Q6 for ? ( PA6 PE6 ) 

im making it for a 4 cyl wasted spark batch fire engine so im populating just the circuits i need only

**Comment by Tjeerdie** [comment]
Q12 is visual feedback that the board is running (PA6 is same pin as the onboard led) so not strictly necessary 
Q6 is for the cooling FAN relay. If you want the radiator cooling fan controlled from the speeduino

**Comment by pkagiantas** [comment]
cool so board will run with both of those circuits unpopulated correct ? 

also i haven't seen a clutch input have you made it or i am just that blind ? :P

**Comment by Tjeerdie** [comment]
You would loose aforementioned functionality, nothing else. You could use one of the unused inputs (analog) for clutch.

**Comment by pkagiantas** [comment]
so for the clutch do i need to use a darlington array like the 0.4.3 boards or the bard can handle it 
and witch pins are unused and analog on the stm ? the ones on the Proto area are free unused ? 
and lets say that the pin PA3 is the clutch input how do we set it in tuner studio ? 
sorry for so many questions but i haven't use that board at all

**Comment by Tjeerdie** [comment]
For example use AIN_3 for this, if the board is build correctly it should be 15 Volt safe. (never tested so on your own risk). The best way is to remove R57, Make R61 1k. But that is not strictly necessary.  Make sure the bat54s is in place! That is your voltage safety.
 
ECU pin 20 as input
MCU input PA1 that has number 49 (so use 49 in Tuner Studio).

**Comment by pkagiantas** [comment]
thanks im gonna try your way :) 👍
