### ISSUE TITLE
Sd datalog 

### ISSUE THREAD

**Issue by pkagiantas** [Tjeerdie/SPECTRE#6]
im facing a strange issue with the sd card datalog 
and i cant seem to make it work 

some times it starts logging fine and others i get the sd er and it wont work 

have you faced the same issue before ? do you need any more info or tests ?

**Comment by Tjeerdie** [comment]
Ah sdcard logging is not SPECTRE specifically ;-). Couple of questions:
- Is the sdcard formatted FAT16 or FAT32? 
- Is a file created on the sdcard or no file is created at all?
- Do not install de STM32SD library, that one does that type of errors and more. The corrected library is included in the PR.

**Comment by pkagiantas** [comment]
i have to check on the library i cant remember which one i have
the card is fat32 the file is there some times 0kb size tho

**Comment by pkagiantas** [comment]
STM32RTC is the library  i use

**Comment by Tjeerdie** [comment]
> STM32RTC is the library i use

That's correct. Did you set the RTC time correct? And is the file created with correct time and date?

**Comment by pkagiantas** [comment]
yeah files are created with the correct time stamp as a name 
it inconsistent when it will work or not 
for example today i started the bike 10 times and i got 5-6 files with partial logs some times it runs ok sometimes it starts logging and then stops and sometime it will start with the sd er from the getgo

**Comment by Tjeerdie** [comment]
Hmm i had similar issues when i started the Sdcard project. Issues where related to other interrupts running and interrupting Sdcard writes. That stopped the logging at random. But that shouldn't be the case anymore. 

I assume you tried various sd-cards? I never had a issue with any. When i have time, next week or something, i wil try a fresh install and see if it happens to me too.

**Comment by pkagiantas** [comment]
i have tried three sd cards two are the same brand 8gb and one is a 64g that is not working at all :P 
im using this release https://github.com/Tjeerdie/speeduino  if that makes any difference

**Comment by Tjeerdie** [comment]
Welll I updated that without checking with a longer log if Sdcard logging still works as expected. Short still worked. If you open a version of couple of weeks back without newest master merged in maybe it changes something. But should still just work. I will try next week when i hopefully have some time.

**Comment by pkagiantas** [comment]
no worries ill try to find an older version to test :D
