### ISSUE TITLE
[Question] Regarding the PPTC fuses

### ISSUE THREAD

**Issue by Griletos** [Tjeerdie/SPECTRE#7]
I'm having a hard time finding PPTC's with the same 16v2a ratings the project requires here in my country.
Closest ones I was able to find are 16v1.5a and 30v2.5a.
Just wanted to know if one of those are suitable, or if I can use standard 2a fuses, or should I really stick to the 16v2a PPTC, in which case I'll import a few.

**Comment by Tjeerdie** [comment]
the 1.5A would be fine. The 2A is just what i had lying around here. 
1. The 5 volt regulator only takes maximum 1A continuous so a 1A fuse would be more than enough. 1A is not even possible without cooling the regulator. 
2. The stepper driver should also not be much more than 1A continuous but i never tested.

**Comment by Griletos** [comment]
Thank you very much, I don't plan on using the stepper driver, so it won't actually pose a problem.
