### ISSUE TITLE
Clutch switch input

### ISSUE THREAD

**Issue by andredalmolin** [Tjeerdie/SPECTRE#9]
Hi!
I'm just finishing the wiring for an Spectre to use in an VW Jetta 2.5 5cyl with turbo.
We wish to use flat shift, but I didnt find an clutch input. There is any unused input that I can reassign to clutch input?

**Comment by Tjeerdie** [comment]
Sorry for the late response, but maybe someone else can still sue this

You could try use the flex fuel input pin, if you do not have a flex fuel sensor connected
